0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,25 @@
 #!/usr/bin/env bash
-# Transfers a file from our client to a server
-#
-# variables
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# This script transfers a file from the client to a server using SCP.
+
+# Check if the number of arguments is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign arguments to variables
+path_to_file="$1"
+ip="$2"
+username="$3"
+path_to_ssh_key="$4"
+
+# Use SCP to transfer the file to the user's home directory on the server
+scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip":~/
+
+# Check the SCP exit status to see if the transfer was successful
+if [ $? -eq 0 ]; then
+    echo "File successfully transferred."
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "Error transferring file."
+    exit 1
 fi
